#!/bin/sh -e

### BEGIN INIT INFO
# Provides:          startupsound
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Should-Start:      autofs $network $named alsa-utils pulseaudio avahi-daemon
# Should-Stop:       autofs $network $named alsa-utils pulseaudio avahi-daemon
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a sound at boot
### END INIT INFO

aplay -q /home/pi/miek/sounds/rise1.wav 2>&1 >/dev/null &
